//
// Recipe.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct Recipe: Codable { 


    public var title: String?
    public var ingredients: String?
    public var thumbnail: String?

    public init(title: String?, ingredients: String?, thumbnail: String?) {
        self.title = title
        self.ingredients = ingredients
        self.thumbnail = thumbnail
    }

}
